# Generated by Django 5.0.3 on 2026-06-19 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoothOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_number', models.CharField(max_length=30, unique=True)),
                ('booth_id', models.CharField(max_length=20)),
                ('constituency', models.CharField(max_length=100)),
                ('is_session_active', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booth_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_id', models.CharField(max_length=25)),
                ('result', models.CharField(choices=[('approved', 'Approved'), ('rejected_no_match', 'Rejected — Fingerprint No Match'), ('rejected_already_voted', 'Rejected — Already Voted'), ('rejected_not_enrolled', 'Rejected — Not Found'), ('fallback_otp', 'Approved via OTP Fallback')], max_length=30)),
                ('match_score', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_biometric_exempt', models.BooleanField(default=False)),
                ('booth', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booth.boothofficer')),
            ],
        ),
    ]
