# Generated by Django 5.0.3 on 2026-06-19 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_number', models.CharField(max_length=30, unique=True)),
                ('constituency', models.CharField(max_length=100)),
                ('is_active_session', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='officer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_id', models.CharField(blank=True, max_length=25, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Transgender / Other')], max_length=1)),
                ('relative_name', models.CharField(max_length=150)),
                ('relation', models.CharField(choices=[('father', 'Father'), ('husband', 'Husband'), ('mother', 'Mother'), ('guardian', 'Guardian')], max_length=10)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('house_number', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('state', models.CharField(default='Karnataka', max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('assembly_constituency', models.CharField(max_length=150)),
                ('parliamentary_constituency', models.CharField(blank=True, max_length=150)),
                ('assigned_booth', models.CharField(blank=True, max_length=100)),
                ('aadhaar_hash', models.CharField(max_length=64, unique=True)),
                ('passport_photo', models.ImageField(blank=True, null=True, upload_to='voter_photos/')),
                ('fingerprint_template', models.BinaryField(blank=True, null=True)),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('deceased', 'Deceased'), ('migrated', 'Migrated')], default='pending', max_length=15)),
                ('has_voted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrolled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='voters.enrollmentofficer')),
            ],
        ),
    ]
