# Generated by Django 5.0.3 on 2026-06-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='house_number',
            field=models.CharField(max_length=150),
        ),
    ]
