# Generated by Django 5.0.3 on 2026-06-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FraudAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('duplicate_vote', 'Duplicate Vote Attempt'), ('duplicate_aadhaar', 'Duplicate Aadhaar on Enrollment'), ('fingerprint_mismatch', 'Repeated Fingerprint Mismatch'), ('dead_voter', 'Deceased Voter Attempt'), ('cross_constituency', 'Cross-Constituency Vote Attempt')], max_length=30)),
                ('voter_id', models.CharField(max_length=25)),
                ('booth_id', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
