# Generated by Django 6.0.3 on 2026-06-20 17:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_type', models.CharField(max_length=50)),
                ('data', models.JSONField()),
                ('previous_hash', models.CharField(max_length=64)),
                ('hash', models.CharField(blank=True, max_length=64)),
            ],
        ),
    ]
